local/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'MainController@index');
Route::post('/feedback', 'MainController@feedback');
Route::post('/subscriber', 'MainController@subscriber');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('/admin', 'HomeController@index');


Route::group(['prefix' => 'admin','middleware' => ['auth']], function()
{

    Route::get('home', 'HomeController@index');
	Route::resource('group', 'GroupController');
	// Route::resource('permission', 'PermissionController');
	Route::resource('subscriber', 'SubscriberController');
	Route::resource('feedback', 'FeedbackController');
	Route::resource('user', 'UserController');
    Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
	// Route::resource('news', 'NewsController');    	
	// Route::resource('subscriber', 'SubscriberController');
	// Route::resource('client_contact', 'Client_ContactController');
});

local/app/Http/Controllers/GroupController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Model\Group;
use App\Model\User;
use App\Model\Permission;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateGroupFormRequest;
use App\Http\Requests\UpdateGroupFormRequest;

use Illuminate\Http\Request;

class GroupController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$groups = Group::all();		
		 return View('group.index', compact('groups'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{		 
		 return View('group.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateGroupFormRequest $request)
	{
		
		$group = Group::create(['name'=>$request->input('name'),							
								'created_by'=>\Auth::user()->id]);
		 return redirect('admin/group');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$group = Group::where('id',$id)
		                        ->get();
		return View('group.show', compact('group'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$group = Group::find($id);
		
		 return View('group.edit', compact('group'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id,UpdateGroupFormRequest $request)
	{
		$result =Group::where('id', $id)->update(['name' => $request->input('name'),											'updated_by'=>\Auth::user()->id]);
		return redirect('admin/group');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$result =Group::destroy($id);
		return redirect('admin/group');
	}

}

local/resources/views/group/create.blade.php
@extends('app')
@section('content')

 <section class="content-header">
          <h1>
            Group
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{url('/admin/group')}}"> Group</a></li>
          </ol>
        </section>
	

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
					<h3 class="box-title">Create</h3>
                </div>
                <div class="box-body">
					@if($errors->any())
						<div class="alert alert-danger">
							@foreach($errors->all() as $error)
								<p>{{ $error }}</p>
							@endforeach
						</div>
					@endif
					 
					{!! Form::open(['route' => 'admin.group.store']) !!}
						<div class="form-group">
							{!! Form::label('name', 'Name') !!}
							{!! Form::text('name',null,array('class'=>'form-control')) !!}
						</div>
						                    
						{!! Form::submit('Create',array('class'=>'btn btn-primary')) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>	
</section>
 

@endsection

local/resources/views/group/edit.blade.php
@extends('app')
@section('content')

 <section class="content-header">
           <h1>
            Group
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{url('/admin/group')}}"> Group</a></li>
          </ol>
        </section>
	

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
					<h3 class="box-title">Edit</h3>
                </div>
                <div class="box-body">
					@if($errors->any())
						<div class="alert alert-danger">
							@foreach($errors->all() as $error)
								<p>{{ $error }}</p>
							@endforeach
						</div>
					@endif
					{!! Form::model($group,['route' => ['admin.group.update', $group->id], 'method' => 'patch']) !!}
						<div class="form-group">
							{!! Form::label('name', 'Name') !!}
							{!! Form::text('name',null,array('class'=>'form-control')) !!}
						</div>
						
						{!! Form::submit('Edit',array('class'=>'btn btn-primary')) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>	
</section>
 
@endsection

local/resources/views/group/index.blade.php
@extends('app')
@section('content')

	<section class="content-header">
	  <h1>
		Groups
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Group</li>
	  </ol>
	</section>
		
		

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
				<div class="box-header">
					<a href="{{url('/admin/group/create')}}" class="btn btn-primary"> Add Group</a>
                </div>
                <div class="box-body">
					<div class="table-responsive">
					<table id="example1" class="table table-bordered table-hover table-striped">
					<thead>
						<th>Id</th>
						<th>Name</th>					
						<th>Created Date</th>
						<th>Action</th>
					</thead> 
					<tbody>
					<?php $i =1; ?>
						@foreach($groups as $group)
						<tr>
							<td>{{$i}}</td>
							<td>{{$group->name}}</td>
							<td>{{$group->created_at->format('M d, Y')}}</td>
							<td>
								<a href="{{ route('admin.group.edit', $group->id) }}" class="btn btn-primary pull-left">Edit</a>
								
								{!! Form::open(['method' => 'DELETE', 'route'=>['admin.group.destroy', $group->id],'onsubmit' => 'return confirm("Do you want to delete this data?")']) !!}
								{!! Form::submit('Delete', ['class' => 'btn btn-primary pull-left']) !!}
								{!! Form::close() !!}
							</td>				
						</tr>							
						<?php $i++;?>
						@endforeach
					</tbody>
					</table>
					
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

local/resources/views/group/show.blade.php
/home/developers/public_html/webpower/power/app/views/chargers/show.blade.php