local/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'MainController@index');
Route::post('/feedback', 'MainController@feedback');
Route::post('/subscriber', 'MainController@subscriber');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('/admin', 'HomeController@index');


Route::group(['prefix' => 'admin','middleware' => ['auth']], function()
{

    Route::get('home', 'HomeController@index');
	Route::resource('group', 'GroupController');
	// Route::resource('permission', 'PermissionController');
	Route::resource('subscriber', 'SubscriberController');
	Route::resource('feedback', 'FeedbackController');
	Route::resource('user', 'UserController');
    Route::get('changepassword',['as' => 'admin.changepassword','uses' =>'UserController@changepassword']);
    Route::post('updatepassword',['as' => 'admin.updatepassword','uses' =>'UserController@updatepassword']);
	// Route::resource('news', 'NewsController');    	
	// Route::resource('subscriber', 'SubscriberController');
	// Route::resource('client_contact', 'Client_ContactController');
});

local/app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Model\Group;
use App\Model\User;
use App\Model\Permission;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserFormRequest;
use App\Http\Requests\UpdateUserFormRequest;
use App\Http\Requests\ChangePasswordFormRequest;
use Illuminate\Http\Request;

class UserController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = User::with('group')->get();
		return View('user.index', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	
		 $groups=Group::get()->lists('name', 'id');		 
		 return View('user.create', compact('groups'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateUserFormRequest $request)
	{
		$user =User::create(['name'=>$request->input('name'),
							'email'=>$request->input('email'),
							'username'=>$request->input('username'),
							'password'=>\Hash::make($request->input('username')),
							'gender'=>$request->input('gender'),
							'phone'=>$request->input('phone'),
							'status'=>$request->input('status'),
							'group_id'=>$request->input('group_id'),
							'created_by'=>\Auth::user()->id]);
		if($user){
		$request->session()->flash('success-message', 'User created Successfully.');
		 return redirect('admin/user');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$user = User::where('id',$id)
		                        ->get();
		return View('user.show', compact('user'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		 $user = User::find($id);
		 $groups=Group::get()->lists('name', 'id');
		
		 return View('user.edit', compact('user','groups'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id,UpdateUserFormRequest $request)
	{
		$result =User::where('id', $id)->update(['name' => $request->input('name'),
												'email'=>$request->input('email'),
												'username'=>$request->input('username'),
												'password'=>\Hash::make($request->input('username')),
												'gender'=>$request->input('gender'),
												'phone'=>$request->input('phone'),
												'status'=>$request->input('status'),
												'group_id'=>$request->input('group_id'),
												'updated_by'=>\Auth::user()->id]);
		if($result){
		$request->session()->flash('success-message', 'User updated Successfully.');
		 return redirect('admin/user');
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$result =User::destroy($id);
		if($result){
		$request->session()->flash('success-message', 'User updated Successfully.');
		 return redirect('admin/user');
		}
	}

	public function changepassword()
	{
		
		return View('user.changepassword');
	}

	public function updatepassword(ChangePasswordFormRequest $request)
	{
		
        $user = \Auth::user();
		
		if (!\Hash::check($request->input('old_password'), $user->password)) {
			return redirect('admin/changepassword')->withErrors([
						'old_password' => 'Old password did\'nt matched with user password.'
					]);
		} else {
			
			$user->password =\Hash::make($request->input('password'));
			$user->save();

			$request->session()->flash('success-message', 'User password has been changed.');

			return redirect('/admin/user');
		}
		
	}
	
	

}

local/resources/views/user/changepassword.blade.php
@extends('app')
@section('content')

<section class="content-header">
          <h1>
            Change Password
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{url('/admin/changepassword')}}"> Change Password</a></li>
          </ol>
        </section>


<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
					<h3 class="box-title">Create</h3>
                </div>
                <div class="box-body">
					@if($errors->any())
						<div class="alert alert-danger">
							@foreach($errors->all() as $error)
								<p>{{ $error }}</p>
							@endforeach
						</div>
					@endif
					 
					{!! Form::open(['route' => 'admin.updatepassword']) !!}
					<div class="form-group">
						{!! Form::label('old_password', 'Old Password',['class'=>'control-label']) !!}
						{!! Form::password('old_password',array('class'=>'form-control required ','data-trigger'=>'change focusout','data-required-message'=>'Please enter old password')) !!}
					</div>
					<div class="form-group">
						{!! Form::label('password', 'New Password',['class'=>'control-label']) !!}							
						{!! Form::password('password',array('class'=>'form-control required ','data-trigger'=>'change focusout','data-required-message'=>'Please enter password')) !!}
					</div>
					<div class="form-group">
						{!! Form::label('confirm_password', 'Confirm Password',['class'=>'control-label']) !!}
						{!! Form::password('confirm_password',array('class'=>'form-control required','data-trigger'=>'change focusout','data-equalto'=>'#password','data-required-message'=>'Please re-enter password','data-equalto-message'=>'Password didn\'t match with confirm password')) !!}
					</div>
						{!! Form::submit('Change Password',array('class'=>'btn btn-primary')) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>	
</section>

@endsection

local/resources/views/user/create.blade.php
@extends('app')
@section('content')

 <section class="content-header">
          <h1>
            Users
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{url('/admin/user')}}"> User</a></li>
          </ol>
        </section>
	

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
					<h3 class="box-title">Create</h3>
                </div>
                <div class="box-body">
					@if($errors->any())
						<div class="alert alert-danger">
							@foreach($errors->all() as $error)
								<p>{{ $error }}</p>
							@endforeach
						</div>
					@endif
					 
					{!! Form::open(['route' => 'admin.user.store']) !!}
						<div class="form-group">
							{!! Form::label('name', 'Name') !!}
							{!! Form::text('name',null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
							{!! Form::label('username', 'Username') !!}
							{!! Form::text('username',null,array('class'=>'form-control')) !!}
							
						</div>
						<div class="form-group">
							{!! Form::label('email', 'Email') !!}
							{!! Form::text('email',null,array('class'=>'form-control')) !!}
						</div>
						
						<div class="form-group">
							{!! Form::label('phone', 'Phone') !!}
							{!! Form::text('phone',null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
							{!! Form::label('gender', 'Gender',['class'=>'control-label']) !!}
							{!! Form::radio('gender', 'male',true) !!}
							{!! Form::label('gender', 'Male') !!}
							{!! Form::radio('gender', 'female') !!}
							{!! Form::label('gender', 'Female') !!}
						</div>
						<div class="form-group">
							{!! Form::label('group_id', 'Group') !!}
							{!! Form::select('group_id',array(null=>'Please Select')+$groups,null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
								{!! Form::label('status', 'Status',['class'=>'control-label']) !!}
								{!! Form::radio('status', '1', true) !!}
								{!! Form::label('status', 'Active') !!}
								{!! Form::radio('status', '0') !!}
								{!! Form::label('status', 'Inactive') !!}
						</div>
                        
						{!! Form::submit('Create',array('class'=>'btn btn-primary')) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>	
</section>
 

@endsection

local/resources/views/user/edit.blade.php
@extends('app')
@section('content')

 <section class="content-header">
           <h1>
            User
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{url('/admin/user')}}"> User</a></li>
          </ol>
        </section>
	

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
					<h3 class="box-title">Edit</h3>
                </div>
                <div class="box-body">
					@if($errors->any())
						<div class="alert alert-danger">
							@foreach($errors->all() as $error)
								<p>{{ $error }}</p>
							@endforeach
						</div>
					@endif
					{!! Form::model($user,['route' => ['admin.user.update', $user->id], 'method' => 'patch']) !!}
						<div class="form-group">
							{!! Form::label('name', 'Name') !!}
							{!! Form::text('name',null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
							{!! Form::label('username', 'Username') !!}
							{!! Form::text('username',null,array('class'=>'form-control')) !!}
							
						</div>
						<div class="form-group">
							{!! Form::label('email', 'Email') !!}
							{!! Form::text('email',null,array('class'=>'form-control')) !!}
						</div>
						
						<div class="form-group">
							{!! Form::label('phone', 'Phone') !!}
							{!! Form::text('phone',null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
							{!! Form::label('gender', 'Gender',['class'=>'control-label']) !!}
							{!! Form::radio('gender', 'male',true) !!}
							{!! Form::label('gender', 'Male') !!}
							{!! Form::radio('gender', 'female') !!}
							{!! Form::label('gender', 'Female') !!}
						</div>
						<div class="form-group">
							{!! Form::label('group_id', 'Group') !!}
							{!! Form::select('group_id',array(null=>'Please Select')+$groups,null,array('class'=>'form-control')) !!}
						</div>
						<div class="form-group">
								{!! Form::label('status', 'Status',['class'=>'control-label']) !!}
								{!! Form::radio('status', '1', true) !!}
								{!! Form::label('status', 'Active') !!}
								{!! Form::radio('status', '0') !!}
								{!! Form::label('status', 'Inactive') !!}
						</div>
                        
						{!! Form::submit('Edit',array('class'=>'btn btn-primary')) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>	
</section>
 
@endsection

local/resources/views/user/index.blade.php
@extends('app')
@section('content')

	<section class="content-header">
	  <h1>
		Users
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="{{url('/admin/home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">User</li>
	  </ol>
	</section>
		
		

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
					<div class="box-header">
					<a href="{{url('/admin/user/create')}}" class="btn btn-primary"> Add User</a>
                </div>
                <div class="box-body">
					<div class="table-responsive">
					<table id="example1" class="table table-bordered table-hover table-striped">
					<thead>
						<th>Id</th>
						<th>Name</th>
						<th>Username</th>
						<th>Email</th>
						<th>Group</th>
						<th>Status</th>							
						<th>Created Date</th>
						<th>Action</th>
					</thead> 
					<tbody>
					<?php $i =1; ?>
						@foreach($users as $user)
						<tr>
							<td>{{$i}}</td>
							<td>{{$user->name}}</td>
							<td>{{$user->username}}</td>
							<td>{{$user->email}}</td>
							<td>
								@if(is_object($user->group))
									{{$user->group->name}}
								@endif
							</td>
							<td>{{($user->status=='1')?'Active':'Inactive'}}</td>							
							<td>{{$user->created_at->format('M d, Y') }}</td>
							<td>
								<a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-primary pull-left">Edit</a>
								{!! Form::open(['method' => 'DELETE', 'route'=>['admin.user.destroy', $user->id],'onsubmit' => 'return confirm("Do you want to delete this data?")']) !!}
								{!! Form::submit('Delete', ['class' => 'btn btn-primary pull-left']) !!}
								{!! Form::close() !!}
							</td>				
						</tr>							
						<?php $i++;?>
						@endforeach
					</tbody>
					</table>
					
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

local/resources/views/user/show.blade.php
/home/developers/public_html/webpower/power/app/views/chargers/show.blade.php